name: Automatically create patch release every 2 weeks
on:
  schedule:
    # Run every Friday right before midnight
    - cron: '59 23 * * 5'
jobs:
  create_patch_release:
    uses: dequelabs/axe-api-team/.github/workflows/auto-patch-release.yml
    secrets: inherit
    with:
      release-command: npx standard-version --release-as="${{ github.event.inputs.releaseLevel }}"
      release-branch: master
      default-branch: develop
