name: Create release candidate

on:
  workflow_dispatch:
    inputs:
      releaseLevel:
        description: 'Release level: major, minor, or patch.'
        required: true
        default: 'patch'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        # There is no `package-lock.json` file
      - run: npm install
      - name: Configure git
        run: |
          git config user.name "API Team CI User"
          git config user.email "aciattestteamci@deque.com"
      - id: release
        name: Release
        run: |
          npx standard-version --release-as="${{ github.event.inputs.releaseLevel }}"
          Version=$(jq -r .version package.json)
          echo "::set-output name=Version::$Version"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release
          branch-suffix: timestamp
          title: 'chore: release v${{ steps.release.outputs.Version }}'
          # If there are any changes not already committed, they will be added to
          # a commit with this as the message.
          # If there are no changes no commit will be created.
          commit-message: 'chore: applying release changes'
